### ISSUE TITLE
Panoptic GT labels for 1/10 points

### ISSUE THREAD

**Issue by huiserwang** [BraveGroup/PSPS#2]
Hi Junsong,

Thanks for your good job: "Pointly-Supervised Panoptic Segmentation". I'm interested in it and want to have a try. However, I encounter an issue that I don't have point gt panoptic labels,  "panoptic_train2017_10pnt/1pnt_uniform_dynamic" and "voc_panoptic_train_aug_1pnt_uniform", for COCO2017 and VOC, respectively. Could you please directly provide them for me or provide a script that can generate them myself for me?

Best regards,

**Comment by js-fan** [comment]
Hi, thanks a lot for your interest! 
Please check the generated labels used in the paper in this [link](https://drive.google.com/drive/folders/19qBN_da_icbXvMFjlFtz4y24CN2MAvXB?usp=sharing). I translated the VOC label format into the COCO style, so the validation gt masks are also provided for convenience. Good luck!

**Comment by huiserwang** [comment]
Thank you very much for your sharing! I will close this issue later.
