### ISSUE TITLE
Could you please provide voc_panoptic_train_aug?

### ISSUE THREAD

**Issue by huiserwang** [BraveGroup/PSPS#3]
Hi Junsong,
    Could you please provide voc_panoptic_train_aug for me? I have tried the download link you put in README but no 'voc_panoptic_train_aug' is provided. Thanks for your great work again!

**Comment by huiserwang** [comment]
Sorry for opening a new issue since I can't contact you through the email. It looks like that your email has been deleted from the email system.

**Comment by js-fan** [comment]
Hi, thank you for the question. 'voc_panoptic_train_aug' contains simply the fully-supervised GT labels (of the colormap format). For weakly supervised learning, 'voc_panoptic_train_aug_xpnt_uniform.tar.gz' should be used. I have updated the link folder to also include these full GT labels. Good luck!

**Comment by huiserwang** [comment]
Thank you for your sharing! I will close this issue.

Best regards.
