### ISSUE TITLE
point annotation color

### ISSUE THREAD

**Issue by wendyhuang2021** [BraveGroup/PSPS#5]
I wanted to know the point-label information and tried to extract information from the images in the `voc_panoptic_train_aug_1pnt_uniform` folder. However, I found some colors (e.g., [142, 0, 30] in 2007_000032.png) are not defined in `voc_panoptic_val.json`. Can you tell me how to get the category ID from the RGB color? Or is there a better method to extract information from point labels?

I also found the `get_color` method in the `IdGenerator` class. Can I infer that colors within +/- 30 are in the same class? For example:
<pre>
point annotation     ->   category predefined
[ 142,   0,  30]     ->   (128, 0, 0): cateory 1, aeroplane
[ 187, 117, 146]     ->   (192, 128, 128): category 15, person
</pre>

您好，我在 `voc_panoptic_train_aug_1pnt_uniform` 這個資料夾中的 point-label image 中，發現一些不屬於 `voc_panoptic_val.json` 中定義類的類別顏色，例如 `2007_000032.png` 中的 [142, 0, 30] 這個顏色。
我想請教如何獲取這些未定義顏色所屬的類別？目前我還找到`IdGenerator`中的`get_color`方法。請問我可以簡單推論，只要顏色在正負30內的都所屬同一類別嗎？例如：
<pre>
point annotation     ->   category predefined
[ 142,   0,  30]     ->   (128, 0, 0): cateory 1, aeroplane
[ 187, 117, 146]     ->   (192, 128, 128): category 15, person
</pre>

或者說您有更好的獲取point label內容的方式？

**Comment by js-fan** [comment]
Hi, it follows the COCO Panoptic format. The color variance is due to the different instance IDs. You can take a look at the [coco's panoptic API](https://github.com/cocodataset/panopticapi.git) for more information. I think the `converters/panoptic2semantic_segmentation.py` may fit your needs.

**Comment by wendyhuang2021** [comment]
Thank you for your answer!

I have read the link you referenced, and `converters/panoptic2semantic_segmentation.py` does not directly mention how to convert RGB to category ID. The dataset and examples above are from VOC. Asking an ambiguous question was my mistake.

On the other hand,   my guess refered from `panopticapi/utils.py` , `class IdGenerator` ’s  [get_color](https://github.com/cocodataset/panopticapi/blob/7bb4655548f98f3fedc07bf37e9040a992b054b0/panopticapi/utils.py#L42):

```
def get_color(self, cat_id):
        def random_color(base, max_dist=30):
            new_color = base + np.random.randint(low=-max_dist,
                                                 high=max_dist+1,
                                                 size=3)
            return tuple(np.maximum(0, np.minimum(255, new_color)))
        category = self.categories[cat_id]
        if category['isthing'] == 0:
            return category['color']
        base_color_array = category['color']
        base_color = tuple(base_color_array)
        if base_color not in self.taken_colors:
            self.taken_colors.add(base_color)
            return base_color
        else:
            while True:
                color = random_color(base_color_array)
                if color not in self.taken_colors:
                    self.taken_colors.add(color)
                    return color
```
`max_dist=30` -> if one channel's color differnece between the categoy and the instance within -30 ~ +30 means the instance belong to the category. 
If I'm wrong, please tell me.

**Comment by js-fan** [comment]
You're right; colors within the turbulence range should belong to the same *semantic* class.

By the way, I used the same format for both COCO and VOC.
The color is used to mark different instances. You can convert the color to instance ID by the `rgb2id` function in `panopticapi/utils.py`. The ID is also recorded in the xx.json file, where you can find other related information including the `category_id`.

For example: `color: [142, 0, 30]` -> `id: rgb2id(color)=1966222`, and in `voc_panoptic_train_aug.json`, you can find:
```
{
            "image_id": 2007000032,
            "file_name": "2007_000032.png",
            "segments_info": [
                {
                    "id": 128,
                    "category_id": 1,
                    "area": 4083,
                    "bbox": [
                        105,
                        106,
                        270,
                        77
                    ],
                    "iscrowd": 0
                },
                {
                    "id": 1966222,
                    "category_id": 1,
                    "area": 651,
                    "bbox": [
                        134,
                        87,
                        62,
                        32
                    ],
                    "iscrowd": 0
                },
...
```

**Comment by wendyhuang2021** [comment]
Thanks for your answer!
